[package]
name = "scraper_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
scraper = { workspace = true }
syn = "2.0.76"
